### ISSUE TITLE
Bigbluebutton 2.3 beta, i've got this error

### ISSUE THREAD

**Issue by verbavolant** [bigbluebutton/webcams-to-screenshare#1]
> Closing Audio Modal!
< Audio Modal closed!
(node:1) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'parentNode' of undefined
    at __puppeteer_evaluation_script__:2:85
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/ExecutionContext.js:93:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/ExecutionContext.js:32:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:82:19)
    at DOMWorld.evaluate (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:111:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:82:19)
    at Page.evaluate (/usr/src/app/node_modules/puppeteer/lib/Page.js:792:47)
    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:83:27)
    at Page.takePresenter (/usr/src/app/src/core/page.js:10:15)
    at /usr/src/app/src/index.js:73:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ffdixon** [comment]
Can you provide steps to reproduce this on https://demo.bigbluebutton.org/.
